apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: asocial
          artifact-id: 0493d51e-93e7-4f2a-bd2b-c5cb0055af6f
          target-environment: mm-qa-aspm